project/users/views.py
from flask import Blueprint, render_template, redirect, url_for
from project import db
from project.models import User, Work
from project.users.forms import AddForm, DelForm
from flask_login import login_user, login_required, logout_user, current_user

users_blueprint = Blueprint('users', __name__, template_folder='templates/users')


@users_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    error = None
    form = AddForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data

        #!!! Verificar se ha registro igual
        # data = UserRegister.parser.parse_args()
        #
        # if UserModel.find_by_username(data['username']):
        #     return {"message": "name already taken"}, 400


        new_user = User(name, email, password)
        db.session.add(new_user)
        db.session.commit()

        user = User.query.filter_by(email=form.email.data).first()
        login_user(user)

        return redirect(url_for('works.add'))

    return render_template("add_user.html", form=form, error=error)


@users_blueprint.route('/del', methods=['GET', 'POST'])
def del_():
    form = DelForm()
    if form.validate_on_submit():
        _id = form.id.data
        new_user = User.query.get(_id)
        db.session.delete(new_user)
        db.session.commit()

        return redirect(url_for('users.list_users'))
    return render_template("delete_user.html", form=form)


@users_blueprint.route('/list')
def list_users():
    users = User.query.all()
    works = Work.query.all()
    return render_template("list_users.html", all_users=users, all_works = works)


@users_blueprint.route('/profile')
@login_required
def profile_users():
    works = Work.query.filter_by(user_id=current_user.id)
    alltime_work = Work.query.filter_by(user_id=current_user.id).count()
    return render_template("profile.html", alltime_work=alltime_work, name=current_user.name,
                           id_=current_user.id, working=current_user.working, all_works=works)

project/works/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from project import db
from project.models import Work, User
from project.works.forms import AddForm, RegistrationForm
from flask_login import login_user, login_required, logout_user, current_user
from datetime import datetime

works_blueprint = Blueprint('works', __name__, template_folder='templates/works')


@works_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    works = Work.query.filter_by(user_id=current_user.id)
    form = RegistrationForm()
    time = datetime.now()
    try:
        id_ = current_user.id
        user_work = User.query.get(id_)
        work_final = Work.query.filter_by(user_id=current_user.id).order_by(Work.id.desc()).first()
        time = datetime.now() - work_final.time_init
        if work_final.time_init.strftime("%x") == datetime.now().strftime("%x") and not user_work.working:
            return render_template('index.html', actives=False)
            pass

    except:
        pass

    if request.method == "POST":
        id_ = current_user.id
        user_work = User.query.get(id_)

        if not user_work.working:
            user_work.working = True
            name = request.form.get("name")
            local = request.form.get("local")
            time_init = datetime.now()
            new_work = Work(name,local, id_, time_init)
            db.session.add(new_work)
        else:
            user_work.working = False
            work_final.time_final = datetime.now()
            db.session.add(work_final)
        db.session.add(user_work)
        db.session.commit()

        return redirect(url_for("works.add"))
    return render_template("add_work.html", time=time, form=form, works=works, active=current_user.working, name=current_user.name)


@works_blueprint.route('/profile_work', methods=['GET', 'POST'])
@login_required
def profile_work():
    works = Work.query.filter_by(user_id=current_user.id)
    form = RegistrationForm()
    time = datetime.now()

    if False:
        return redirect(url_for("works.add"))
    return render_template("profile_work.html")

project/templates/index.html
{%extends "model-page.html"%}
{%block content%}
<div class = "mid">
    <div class = "container_mid" id="reg">
            {% if actives%}
        <h2>APRESENTAÇÃO</h2><br>
        <p>projeto de treino ->  Flask, SQL, HTML & JavaS</p><br>
            {% else %}
        <h2>O seu perfil não tem mais atividades hoje.</h2><br>
            {% endif %}
    </div>
</div>


{%endblock%}

project/templates/login.html
{%extends "model-page.html"%}
{%block content%}

<div class = "mid">
    <div class = "container_mid">
        <h2>Login for Access</h2>
        <form action="" method="POST">
          <ul class = "">
              {% if current_user.is_authenticated %}

              <div class="form-item">
                  <span class="material-icons">label</span>
                  <h2><a href="{{url_for('logout')}}">logout</a></h2>

              </div>
              {%else%}

            <div class="form-item">
                  <span class="material-icons">label</span>
                  {{form.hidden_tag()}}
                  {{form.email.label}}{{form.email()}}

                </div>
              <div class="form-item">
                  <span class="material-icons">label</span>
                  {{form.hidden_tag()}}
                  {{form.password.label}}{{form.password()}}
                </div>
            <br>
            <button type="submit" {{form.submit}} Enter</button>
            <br>
            <p>New User ?</p> <a href="users/add">Create an Account</a>
              {% endif %}
          </ul>
        </form>
    </div>
</div>

{%endblock%}

project/templates/model-footer.html
<div class = "container_footer">
    <div class = "row_footer">
        <div class = "footer_col">
            <h4>Author</h4>
            <ul>
                <li><a href="#">About</li></a>
                <li><a href="https://github.com/FerLK">GitHub</li></a>
            </ul>
        </div>
        <div class = "footer_col">
            <h4>Projects</h4>
            <ul>
                <li><a href="https://python-rest-1.herokuapp.com/"><font size="4">Heroku - Store BackEnd</font></a></li>
                <li><a href="#"><font size="4">Under Construction</font></a></li>
            </ul>
        </div>
        <div class = "footer_col">
            <h4>Contact</h4>
            <ul>
                <li><a href="https://www.google.com/maps/place/Curitiba,+PR/@-25.4950501,-49.4298839,11z/data=!3m1!4b1!4m5!3m4!1s0x94dce35351cdb3dd:0x6d2f6ba5bacbe809!8m2!3d-25.4372382!4d-49.2699727">Adress</a></li>
                <li><a href="#">Phone</a></li>
            </ul>
        </div>
        <div class = "footer_col">
            <h4>Social</h4>
            <div class="social-links">
             <!–class="fab fa-facebook-f" –>
                <a href="https://twitter.com/lfkraft"><i class="fab fa-twitter"></i>          </a>
                <a href="https://www.instagram.com/fer.stl/"><i class="fab fa-instagram"></i>         </a>
                <a href="https://www.linkedin.com/in/luiz-fernando-kraft-gallego-736267180/"><i class="fab fa-linkedin-in"></i>      </a>
                
            </div>
        </div>
    </div>
</div>

project/templates/model-header.html
<img class="logo" src="/static/images/clock.png" alt="" >
<nav>
    <ul class = "nav_links">
        <li><a href="{{url_for('index')}}">Home</a></li>
        <li><a href="{{url_for('works.add')}}">Initiate</a></li>
        <li><a href="{{url_for('users.profile_users')}}">Profile</a></li>
        <li><a href="{{url_for('works.profile_work')}}">Works</a></li>
        <li><a class ="cta" href="{{url_for('login')}}"><button>sign</button></a></li>
    </ul>
</nav>
<div id = "clock">
    <p id = "time"></p>
    <p id = weekDay></p>
</div>

project/templates/model-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title> </title>
    
    <link rel="stylesheet" href="/static/css/master.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body class="d-flex flex-column">
   <div id="page-container">
   <div id="content-wrap">
    <header>
        {% include "model-header.html"%}
    </header>
    <main>
        <div class="background"></div>

        {%block content%}
        {%endblock%}
    </main>

    </div>
    <footer id="footer" >
        {% include "model-footer.html"%}
    </footer>
    </div>

    <script type = "application/javascript" src = "/static/clock.js"></script>

</body>



</html>